- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "hi my name is : {{MYNAME | default('NAVE-EN')}}"

- name: Uppercase
  hosts: localhost
  vars:
    greetings: "hello, gm"
  tasks:
  - name: converting to uppercase
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"


- name: lowercase
  hosts: localhost
  vars:
    greet: "HELLO"
  tasks:
  - name: convert to lower
    ansible.builtin.debug:
      msg: "{{greet | lower}}"
  
- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,1,2,2,3,3,3,4,4,5]
  tasks:
  - name: unique numbers
    ansible.builtin.debug:
      msg: "{{ numbers | unique}}"

- name: min and mx
  hosts: localhost
  vars:
    ages: [25,35,15,68,6]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "min age: {{ages | min}}, max age: {{ ages | max}}"

- name: convert dict to items/list
  hosts: localhost
  vars:
    my_dict:
      course: devops-ansible
      trainer: "siva"
      duration: 120 hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "before convert: {{my_dict}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "after convert: {{ my_dict | dict2item}}"

- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"
    


     