- name: installing packages
  hosts: web
  become: yes
  tasks:
  - name: installing pckgs in a loop
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - mysql
      - nginx
